from pathlib import Path

RELATIVE_VANILLA_OVERRIDES_PATH = Path("vanilla")

RELATIVE_ITEMS_PATH = Path("assets/minecraft/items")
RELATIVE_VANILLA_MODELS_PATH = Path("assets/minecraft/models")
RELATIVE_BLOCKSTATE_PATH = Path("assets/minecraft/blockstates")
RELATIVE_VANILLA_TEXTURES_PATH = Path("assets/minecraft/textures")

RELATIVE_SODIUM_MODELS_PATH = Path("assets/mcme/models")
RELATIVE_SODIUM_TEXTURES_PATH = Path("assets/mcme/textures")

# * blockstates
# * items
# * models
#   * block and item
# * textures
#  * block and item

# Relative suffixes (after assets/<namespace>/) to skip during copytree.
# These are processed separately by the blockstate/item/model pipeline
# These blockstates/items/models/textures will only exist in the generated vanilla pack if a vanilla block or item exists in the RP
IGNORED_ASSET_SUFFIXES = {
    Path("blockstates"),
    Path("items"),
    Path("models"),
    # Unable to ignore the entire textures folder because textures can be used for things like fonts
    Path("textures/block"),
    Path("textures/item"),
}

# Full paths (assets/<namespace>/...) to skip — for namespace-specific dirs
IGNORED_ASSET_PATHS = {
    Path("assets/mcme/sml_load_scopes"),
}

# Per-namespace exceptions to IGNORED_ASSET_SUFFIXES.
# modelengine's own models/items are consumed directly by its model loader,
# not reached by vanilla model-chain walking (unlike minecraft, whose
# models/items are regenerated by processBlockstate/processItem), so nothing
# else would ever copy them - they need to pass through the plain copytree.
NAMESPACE_IGNORE_EXCEPTIONS = {
    "modelengine": {Path("models"), Path("items")},
}

OBJ_MODEL_EXTENSION = ".obj"
VANILLA_MODEL_EXTENSION = ".json"
BLOCKSTATE_EXTENSION = ".json"
ITEM_EXTENSION = ".json"
TEXTURE_EXTENSION = ".png"
MCMETA_EXTENSION = ".mcmeta"
OBJMETA_EXTENSION = ".objmeta"
MTL_EXTENSION = ".mtl"

# Identifiers under this prefix name a model hardcoded in the client
# (builtin/generated, builtin/entity) rather than a file in the pack.
BUILTIN_MODEL_PREFIX = "builtin/"

MCME_NAMESPACE = "mcme"
VANILLA_NAMESPACE = "minecraft"

PACK_MCMETA = "pack.mcmeta"
PACK_PNG = "pack.png"
LICENCE = "license.txt"
README = "README.md"

PARENT_DONE_VALUE = "PARENT DONE"
PARENT_SUFFIX = "_parent"

# Mipmap levels objmc pads each baked texture for, and so the most the terrain
# shader samples an objmc model's texture at. 0 turns their mipmapping off.
OBJMC_MIPMAP_LEVELS = 4

# Blocks the client shifts by a random offset for their position (26.2's
# Blocks: BlockBehaviour.Properties.offsetType XZ or XYZ, copied properties
# included). Every vertex of such a block moves, so objmc's carriers on them
# sit at the block centre, where no shift can carry one into another block.
OFFSET_BLOCKS = frozenset({
    "allium", "azure_bluet", "bamboo", "bamboo_sapling", "blue_orchid",
    "closed_eyeblossom", "cornflower", "crimson_roots", "dandelion", "fern",
    "golden_dandelion", "hanging_roots", "large_fern", "lilac",
    "lily_of_the_valley", "mangrove_propagule", "nether_sprouts",
    "open_eyeblossom", "orange_tulip", "oxeye_daisy", "peony", "pink_tulip",
    "pitcher_plant", "pointed_dripstone", "poppy", "red_tulip", "rose_bush",
    "short_dry_grass", "short_grass", "small_dripleaf", "sulfur_spike",
    "sunflower", "tall_dry_grass", "tall_grass", "tall_seagrass", "torchflower",
    "warped_roots", "white_tulip", "wither_rose",
})
